### PR TITLE
Add `ObjectStateArray` setter pipeline

### PR DESCRIPTION
**Pull request by icsl-Jeon**
Still work in progress. Do not review yet. 

Please see [this issue](https://github.com/LARR-Planning/los-keeper/issues/39) also 😊 

This PR actually describes the full pipeline of how to implement setters for an interface.
You will use this code patter in the future :) 

#### Three steps for input:
`SubscribeCallback` -> `ConvertToPureType` -> `SetterType` 

#### (not this PR) for output:
`GetterType` -> `ConvertToMsgType` -> `PublishInTimerCallback`

### CODE REVIEW

**Comment by YunwooLee94** [comment]
When I saw your code, I already had an inkling. Should I review it and click the "approve" button?
SubscribeCallback -> ConvertToPureType -> SetterType

**Comment by YunwooLee94** [comment]
Ummm, I mean.. I already have understood your intention.

**Comment by YunwooLee94** [comment]
Do u want me to approve this merge. I checked the changes. I ask this question because you wrote down not to review PR at the top.

**Review by YunwooLee94 — APPROVED** [review]

**Comment by YunwooLee94** [comment]
Approved :)

**Comment by icsl-Jeon** [comment]
Please review the last commit and merge if you wish! Good luck

**Pull request merged**
